
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title></title>

    <!-- Bootstrap Core CSS -->
    <link href="/sfe/libs/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/sfe/libs/bootstrap/css/modern-business.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/sfe/libs/bootstrap/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/sfe/index/">HOME</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <?php

                foreach ($menu as $item)
                echo '<li>
                         <a href="/sfe/page/'.$item.'">'.$item.'<?php echo $lol ?></a>
                      </li>'
                ?>

                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Header Carousel -->
<header id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <?php
        $i=0;
        foreach ($images as $image){
            echo'<li data-target="#myCarousel" data-slide-to="'.$i.'"></li>';
            $i++;
        }
        ?>

    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <?php
        $i = 0;
            foreach($images as $image){
                $active = '';
                if($i==0){
                    $active = 'active';
                }
                echo '<div class="item '.$active.'">
                          <div class="fill" style="background-image:url('.$image['url'].');"></div>
                                <div class="carousel-caption">
                                <h2>'.$image['name'].'</h2>
                          </div>
                      </div>';
                $i++;
            }
        ?>



    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
</header>

<!-- Page Content -->
<div class="container">

    <!-- Marketing Icons Section -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                <?php echo $welcomeText; ?>
            </h1>
        </div>
        <?php
        foreach ($content as $item){
            echo '<div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw '.$item['font'].'"></i> '.$item['header'].'</h4>
                </div>
                <div class="panel-body">
                    <p>'.$item['content'].'</p>
                </div>
            </div>
        </div>';
        }
        
        ?>

    </div>
    <!-- /.row -->

    <!-- Portfolio Section -->


    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; SFE 2016 T&A</p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

<!-- jQuery -->
<script src="./../libs/jquery-1.12.3.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="./../libs/bootstrap/js/bootstrap.min.js"></script>

<!-- Script to Activate the Carousel -->
<script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
</script>

</body>

</html>
