<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin Panel</title>

    <!-- Bootstrap Core CSS -->
    <link href="/sfe/libs/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/sfe//libs/admin/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/sfe/libs/admin/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/sfe//libs/admin/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Admin Panel </a>
            <a href="./admin/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
        </div>
        <!-- /.navbar-header -->


        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">

                    <li>
                        <a href="main" class="check-click"><i class="fa fa-dashboard fa-fw"></i> Main Settings</a>
                    </li>
                    <li>
                        <a href="management" class="check-click"><i class="fa fa-table fa-fw"></i> Page Management</a>
                    </li>
                    <?php  if (isset($_SESSION['permission']) AND $_SESSION['permission'] == 'Admin') {
                      echo ' <li>
                        <a href="users" class="check-click"><i class="fa fa-edit fa-fw"></i> Users</a>
                    </li>
                    <li>
                        <a href="other" class="check-click"><i class="fa fa-edit fa-fw"></i> Other</a>
                    </li>';
                    }?>

                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <!-- Page Content -->
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row" id="content">
                <div class="col-lg-12">
                    <h1 class="page-header">Blank</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="/sfe//libs/admin/bower_components/jquery/dist/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/sfe//libs/admin/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="/sfe/libs/admin/bower_components/metisMenu/dist/metisMenu.min.js"></script>

<script src="/sfe/libs/admin/bower_components/datatables/media/js/jquery.dataTables.min.js"></script>
<!-- Custom Theme JavaScript -->
<script src="/sfe//libs/admin/dist/js/sb-admin-2.js"></script>
<script>
   $(document).ready(function(){
       $('.check-click').on('click',function(event){
           event.preventDefault();
           $.ajax({
               url: "/sfe/admin/post",
               type: "POST",
               data: {page : $(this).attr('href')},
               dataType: "html",
               success: function(html){
                   $('#content').html(html);
               }
           });
       })
   });

</script>
</body>

</html>
