<form role="form" id="target">
    <div class="form-group">
        <label>Text Input</label>
        <input name="pageName" class="form-control"  value="tada">
        <p class="help-block">Example block-level help text here.</p>
    </div>
    <div class="form-group">
        <label>Text Input with Placeholder</label>
        <input name="tada" class="form-control" value="tada" placeholder="Enter text">
    </div>
    <div class="form-group">
        <label>Text area</label>
        <textarea class="form-control" name="" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-default">Submit Button</button>
    <button type="reset" class="btn btn-default">Reset Button</button>
</form>

<script>
    $( "#target" ).submit(function( event ) {
        event.preventDefault();
        $.ajax({
            url: "/sfe/admin/edit",
            type: "POST",
            data: {page : 'main',
                   data:$('#target').serialize() },
            dataType: "html",
            success: function(html){
                $('#content').html(html);
            }
        });
    });
</script>