
    <?php
    if (isset($message)) {
        foreach ($message as $item) {

            echo '<div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            ' . $item . '
        </div>';
        }
    }
    ?>


        <?php
        if (isset($error)) {
            foreach ($error as $item) {
                echo '<div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            ' . $item . '
        </div>';
            }

        }
        ?>

        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Kitchen Sink
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Login</th>
                                <th>Email</th>
                                <th>Admin</th>
                                <th>Delete</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>1</td>
                                <td>Mark</td>
                                <td>Otto</td>
                                <td>@mdo</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>Jacob</td>
                                <td>Thornton</td>
                                <td>@fat</td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>Larry</td>
                                <td>the Bird</td>
                                <td>@twitter</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <div class="col-lg-6">
            <form role="form" id="targetForm">
                <div class="form-group">
                    <label>login</label>
                    <input name="user_name" class="form-control" value="tada">
                </div>
                <div class="form-group">
                    <label>email</label>
                    <input name="user_email" class="form-control" value="tada">
                </div>
                <div class="form-group">
                    <label>password</label>
                    <input name="user_password_new" class="form-control" value="tada">
                </div>
                <div class="form-group">
                    <label>repeat password</label>
                    <input name="user_password_repeat" class="form-control" value="tada">
                </div>
                <div name template class="form-group">
                    <label>Permission</label>
                    <select name="user_permission" class="form-control">
                        <option>User</option>
                        <option>Admin</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-default">Add User</button>
            </form>


        </div>


        <script>
            $(document).ready(function () {
                $("#targetForm").submit(function (event) {
                    event.preventDefault();
                    $.ajax({
                        url: "/sfe/admin/post",
                        page: 'users',
                        type: "POST",
                        data:  {page : 'users',
                            action: 'add',
                            data:$('#targetForm').serialize() },
                        success :function (html) {
                        $('#content').html(html);
                        }
                        });
                });
            })
        </script>